name: React build
on: 
  push
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: 16
      - name: npm install client
        run: |
          npm run install-client
      - name: react build
        run: |
          npm run build-client
